name: CI

on: [push, pull_request]

jobs:
    build:
        runs-on: ubuntu-latest
        services:
          mongodb:
            image: mongo:4.2.0
            env:
              # Following credentials are only used during testing in docker container
              MONGO_INITDB_ROOT_USERNAME: admin
              MONGO_INITDB_ROOT_PASSWORD: admin
          mongodb-ssl:
            image: rzhilkibaev/mongo-x509-auth-ssl:latest
        steps:
            - uses: actions/checkout@v2
            - name: Set up JDK 11
              uses: actions/setup-java@v1
              with:
                java-version: 11          
            - run: mvn clean install -pl mongo-utils
            - name: Ballerina Build W/O tests
              uses: ballerina-platform/ballerina-action/@swan-lake-connector-release
              with:
                args:
                  build --skip-tests -c mongodb
              env:
                JAVA_HOME: /usr/lib/jvm/default-jvm
                JAVA_OPTS: -DBALLERINA_DEV_COMPILE_BALLERINA_ORG=true
            - name: Ballerina Build W/ tests
              uses: ballerina-platform/ballerina-action/@swan-lake-connector-release
              with:
                args:
                  test --groups mongodb mongodb
              env:
                JAVA_HOME: /usr/lib/jvm/default-jvm
                # Following credentials are only used during testing in docker container
                MONGODB_HOST: mongodb
                MONGODB_USER: admin
                MONGODB_PASSWORD: admin
            - name: Ballerina Build W/ tests (SSL)
              uses: ballerina-platform/ballerina-action/@swan-lake-connector-release
              with:
                args:
                  test --groups mongodb-ssl
              env:
                JAVA_HOME: /usr/lib/jvm/default-jvm
                # Following credentials are only used during testing in docker container
                WORKING_DIR: ./mongodb
                MONGODB_HOST: mongodb-ssl
                MONGODB_USER: C=US,ST=CA,L=San Francisco,O=Jaspersoft,OU=JSDev,CN=admin
            - name: Ballerina Push
              uses: ballerina-platform/ballerina-action/@swan-lake-connector-release
              with:
                  args:
                      push
              env:
                  JAVA_HOME: /usr/lib/jvm/default-jvm
                  WORKING_DIR: ./mongodb
                  BALLERINA_CENTRAL_ACCESS_TOKEN: ${{ secrets.BALLERINA_CENTRAL_ACCESS_TOKEN }}
